### ISSUE TITLE
Cell files save as .png

### ISSUE THREAD

**Issue by wilddoggamer** [GrapeshotGames/ServerGridEditor#2]
Instructions tell us we have to save our cell image files as CellImg_*****.jpg, however, that is not an option on the export screen.

**Comment by GrapeshotGames** [comment]
There is a poorly placed 'Export PNGS' checkbox on the main window once you load a project. It's near the bottom center. Do you have this unchecked? It should really just be removed as an option, since it's not used for the cell images anymore. Let me know if so and I will just remove and push that change up to avoid confusion!

**Comment by chasen** [comment]
For me it actually saved the images in jpeg format they just had the png file extension. I just changed the extension and it worked

**Comment by rezalas** [comment]
Yeah I found that the extension is hard coded. I've got  a fix for it that I'll file a PR for later today.

**Comment by GrapeshotGames** [comment]
Ahh, I see the optional exports. Thanks for the PR and letting us know more. Ok so I fixed up the 'Local Export' to be 'Local Export All' and renamed the other ones to be more clear hopefully. We only really use the Export All here and uncheck/check 'Disable Image Exporting' on the main screen currently.  Local Export also was fixed up to use the local path vs an alternative one for how we have things setup. Let us know how this works now!
