### ISSUE TITLE
Generate Scripts Feature

### ISSUE THREAD

**Issue by rezalas** [GrapeshotGames/ServerGridEditor#23]
I have been building a number of maps, and building the scripts for each one manually is tedious. Given that all the data in the script already exists in the editor, I feel we should have an option to generate scripts as well in the export menu.  I'll work toward a PR with this feature as well as minor cleanup toward DRY in the main form.

**Comment by GrapeshotGames** [comment]
What do you mean by 'scripts' in this case? That part is a little unclear to me. Launch commands?

**Comment by rezalas** [comment]
Sorry, yes the launch commands for each server. All the data for startup is there and it would save me a bit of time being able to click one button to have it dump them all into a file with all the parameters properly formatted with questionmarks

**Comment by smooreace** [comment]
That's relatively impossible since every server, every grid, live under a
completely different path. It would be a total waste of time.

**Comment by rezalas** [comment]
I run clusters of servers in virtual environments out of the same paths on each cluster, and have for years. It works quite well actually with Ark and has worked well for atlas too.

**Comment by smooreace** [comment]
I run 4 Ark clusters and 2 DnL clusters as well... 32 total instances
between them. So I'm well aware if the functionality. But there is no
consistency in directory structure between my work and yours. And in that,
there are at least a dozen other very distinct structures that other people
might find logical to THEM. It's because of that inconsistency that
I'm basing my thoughts on. Ive helped a dozen + communities get their Atlas
servers going. So are VERY mythotical about organization and cleanliness.
Others are absolutely insane messes. Creating cookie-cutter start bat file
simply give more crap to have to rewrite in the end.

**Comment by wartech0** [comment]
I feel like this should be a different program all together, shoe horning this functionality into ServerGridEditor is kinda eh? I've been playing with C# and using the generated ServerGrid.json to automatically spin up processes and it works fine for single server multi grid setups, but it wouldn't work at all in a multi-grid multi-server setup.

**Comment by rezalas** [comment]
Smooreace, if you are well aware of the functionality then you know that every server instance has the exact same internal folder structure, and thus placing startup scripts at the shootergame root with the ServerGrid.json file will not only have the same path every time, but work perfectly as well. I've actually written the feature already, tested it, and used it myself to prove that it all works well with relative pathing. If you need something more complex then you won't be hurt by the feature and it's likely not for you, but nothing stops people from writing more specific scripts or just using these. 

Without providing these there is no other option for some people but to hope for help from someone with more experience like myself, you or someone else. That can lead to good experiences or potentially having to deal with abrasive rude or arrogant individuals, which nobody wants. 

Wartech0 you could be right, I had the idea to include it because the wiki for the editor also includes startup instructions and examples, and I thought it might mean people have an easier time building their first server. I use some automation tooling too but scripts are just easier for me to share with people when I'm helping people get up and running, and it's simple to include a clean build script generator given how the code is built already. As I said, I haven't made a PR for this yet, so if it's not wanted by GrapeshotGames I won't.

**Comment by smooreace** [comment]
I didn't say that YOUR way was wrong or wouldn't work I simply said it
won't work for everyone. The problem is that literally, EVERY how-to that
exists for Ark, DnL, Conan, Atlas, 7DtD.... (I could go on forever) starts
out with all the batch files being at the root of the server, or series of
servers. This is 100% contradictory to your method of filing (and mine in
fact). I didn't say it was a bad idea particularly either. But what will
happen is that it won't easily jive with how the THOUSANDS of people set up
servers that have no clue what they are doing. Those that have zero
computer skill, but can at very least follow terrible instructions. If this
could all be done to work alongside those terrible instructions then it
would lead to vast success. Without, it will lead to mass confusion. I deal
with these illiterates ALL DAY! Its FAR too easy to totally confuse them!

**Comment by GrapeshotGames** [comment]
Most of this seems out of the scope mostly given how varied it can be for people. I can say that we use BaseServerArgs and MachineIdTag internally to generate command lines with launching official servers in other words we have another tool that uses that class library and does it dynamically when they are launched on each machine.
 
For example:
`ServerArgs = ServerArgs.Replace("%AltSaveDir%", AltSaveDirTarget);`
`ServerArgs = ServerArgs.Replace("%PORT%", ServerConfig.gamePort.ToString());`

So feel more than happy to do what works for you locally. Our launcher itself is very simple soon as you cut out some things we have to do special. Just uses env variables and few hardcoded paths to generate command lines and run them. We also have it run our little process monitor/reporter that can auto restart server if it goes down. And that is all there is to it but can be very handy.

With all that said a link to the wiki here or some kind of example might be a good addition of how to use what is generated.
