### ISSUE TITLE
Resets Biome Templates every load

### ISSUE THREAD

**Issue by MapleBaconPancake** [GrapeshotGames/ServerGridEditor#32]
is there a way to prevent island editor from erasing some settings, I always need to redo my biomes and redis info every time i load my save to edit my world

**Comment by smooreace** [comment]
I got tired of it... set everything to read only and its been great ever since! But Ive been doing that for years with Ark

**Comment by smooreace** [comment]
For the record... updates and validations are resetting config files too!

**Comment by rezalas** [comment]
We haven't had any issues with resets or validations deleting our configs, but we run backups just in case before updates since we've been there with Ark before. It's normally only when the servers don't shut down cleanly that we lose the configs.

**Comment by smooreace** [comment]
...even though the configs have no reason to be touched after the first 30
seconds of a load. The problem seems to come when the config isn't set up
in the same order of sections as the default config, so it overwrites it.
Read-Only solves everything permanently! And prevents accidents

**Comment by rezalas** [comment]
I think it's caused when the server closes during the write operation, as it seems to save updated settings to the configs regularly while the server is running (which makes sense since you can change some server settings in-game). I've wondered if it's happening during the automated saveworld operation cycle, but I don't want to be rude and decompile it to look. Save cycles seem to be better with Atlas so far (though RCON connectivity is still a bit buggy).

**Comment by GrapeshotGames** [comment]
Are you running them in same directory with different settings? Without an AltSaveDirectoryName= set? That could cause your games to fight each other.

**Comment by GrapeshotGames** [comment]
Otherwise I'm not fully clear on exact issue you are facing.

**Comment by SteadEXE** [comment]
Easy way to reproduce: Load a 2x2 grid for example, edit cell info it says for example "Template: Tropical", perform a local export. then load the freshly exported ServerGrid.json, the same cell will be set to Template: None. And the issue is: serverTemplates is an empty array in the exported json. The quick fix would be to copy this array at export time. So if you manually copy the serverTemplates array from old to new file, it works.

**Comment by SteadEXE** [comment]
I don't know if it's the issue opened here. But it's a bug in the grid editor.

**Comment by GrapeshotGames** [comment]
Export doesn't save as is. Do you save after you make that change? That is the first thing that comes to mind.

**Comment by ispezz** [comment]
seems to be working fine for me havent had issues with biomes reseting and i have made 100+ maps already for different hosting Company like G-Portal and U-Host, etc...

**Comment by rezalas** [comment]
Yeah I haven't been able to reproduce and I've been actively trying.
________________________________

**Comment by DefualtCoder** [comment]
Line 513 in "Project.cs" - ProjectObj.serverTemplates.Clear(); upon export of serialized ProjectObj the bool must not be triggering for him as export when he does export.

**Comment by GrapeshotGames** [comment]
Ok sounds like just more intuitive saving or asking to save needs to happen in the future from what I gather. Along with some documentation. Made a note and a quick wiki edit with a 'gotcha' on this
