### ISSUE TITLE
Save and Edit button greyed out

### ISSUE THREAD

**Issue by mpowers523** [GrapeshotGames/ServerGridEditor#38]
I downloaded the latest version.  I create project, but the save button is greyed out.

If I load a sample json, I can edit it and save without isuse

**Comment by ispezz** [comment]
works fine for me https://gyazo.com/3de31f3f3403b7b84e9d7483a3e94fa3

make sure u have a map loaded u cant save and edit without a map loaded

**Comment by DefualtCoder** [comment]
Can confirm save/edit menu items are grey upon creation of a new project. 
Fixed by commenting out lines 263, 271 in "mainform.designer.cs". 
For some reason they had "this.saveToolStripMenuItem.Enabled = false;"
and "this.editToolStripMenuItem.Enabled = false;" enabled until a loaded project was applied then it changed those values to true. However on intial creation those values would be false.

**Comment by ayan4m1** [comment]
That was my fault, actually. I changed the way that the menu items get enabled on load and forgot to handle the "create" case. It is addressed in the now-referenced PR.

**Comment by mpowers523** [comment]
Thanks
    	
    	

    	Get Outlook for iOS
    
  



On Sat, Jan 5, 2019 at 6:32 PM -0600, "Andrew DeLisa" <notifications@github.com> wrote:












That was my fault, actually. I changed the way that the menu items get enabled on load and forgot to handle the "create" case. It is addressed in the now-referenced PR.

**Comment by 226612345** [comment]
> 我下载了最新版本。我创建项目，但保存按钮显示为灰色。
> 
> 如果我加载一个样本json，我可以编辑它并保存而不使用
So am I.
