### ISSUE TITLE
Any idea how to generate power stone quest ?

### ISSUE THREAD

**Issue by SteadEXE** [GrapeshotGames/ServerGridEditor#47]
It could be useful to auto generate the power stone quest settings or atleast write a little article on the wiki how to set it up.

**Comment by DefualtCoder** [comment]
I have already put that in place in my personal one as its something of an enhancement or feature that i won't PR to the original repo can be found here:[ServerGridEditorWIP](https://github.com/DefualtCoder/ServerGridEditorWIP)

**Comment by GrapeshotGames** [comment]
It's currently a little convoluted since that data is copied from the editor. The Dev Kit will allow you to do the same thing and deal with any changes over time but there. That is very interesting @DefualtCoder , I wonder how you would deal with the icon refs. It would be cool to have some way to edit this in the tool. Hmmm, guess you could just make a list of 'good' ones and have people add to it or just ignore it as some extra data you are trying to generate that into.

**Comment by DefualtCoder** [comment]
@GrapeshotGames - I could just send you the source if you want it, question is where if not a PR.

**Comment by smooreace** [comment]
This isnt a support forum

**Comment by GrapeshotGames** [comment]
Sure a PR would be good to see. Makes it easier for me to grab :) Sorry for the delay in getting back on this!

**Comment by DefualtCoder** [comment]
@GrapeshotGames - I will clean up the code and push a PR out by Monday then.
