### ISSUE TITLE
Unusual CPU usage in server if date is 2019+

### ISSUE THREAD

**Issue by Psychoboy** [GrapeshotGames/ServerGridEditor#52]
We were having high CPU usage and couldn't figure out with identical configuration. As a last ditch effort we changed "Day0": "2019-01-21 07:57:56" to "Day0": "2018-07-21 07:57:56" and CPU usage dramatically dropped and everything is working great. WHY?

**Comment by smooreace** [comment]
Interesting, but it was likely a fluke. And has nothing to do with the map
editor. If you change the date back to the 2019 date does CPU usage go up?
Ive had several grids boot to a situation where CPU usage was double+ what
was normal. A simple restart fixed it.

**Comment by Psychoboy** [comment]
Oh yeah, many restarts, creating new grids all sorts of things. This was literally the one thing. Wasn't just me either a friend tried and had safe results. I know it use time to keep everything in sync but this was super weird. I've changed the time back to 2019 reset the redis and saves cpu went back up. Again set time back reset the redis and saves. Cpu back normal

**Comment by smooreace** [comment]
Interesting... so I played a little science.

Test criteria:
New 2x2 launching only grid A1 off of a mechanical hard drive
Existing machine thats already running 4 Atlas grids and 14 Ark Servers
4 test launches, and images of the results are below

Launch 1 - Load time 157.31 second

**Comment by smooreace** [comment]
Interesting... so I played a little science.

Test criteria:
New 2x2 launching only grid A1 off of a mechanical hard drive
Existing machine thats already running 4 Atlas grids and 14 Ark Servers
4 test launches, and images of the results are below

Launch 1
Load time 157.31 second
Date set to 2018-12-24
4.64% CPU and 4.42 GB RAM

Launch 2
Load time 26.87 second
Date set to 2019-12-24
6.76% CPU and 4.4 GB RAM

Launch 3
Load time 26.83 second
Date set to 2018-12-24
5.31% CPU and 4.42 GB RAM

Launch 4
Load time 27.33 second
Date set to 2019-12-24
6.74% CPU and 4.4 GB RAM

https://gyazo.com/af01321a2ad9ff8e2fbefb620a4df8da
https://gyazo.com/40812eecabc9472f4ff369ef2924b2be
https://gyazo.com/63eef4fd331b45393f25c0d81bd7379d
https://gyazo.com/992ee33478e55cca1120455d6a78aead

Conclusions...
While a 2019 date did increase CPU usage, so did the second 2018 launch.
1.5% additional CPU simply because of date is very strange and
warrants some investigation. But its hardly something that matters.

**Comment by GrapeshotGames** [comment]
Hmmm... Not seeing anything related to changing that to 2019 vs 2018 times or any jump locally in cpu usage. Since it's more server related vs tool related I recommend posting on https://www.playatlas.com/index.php?/forums/forum/60-dedicated-server-and-developer-tools-discussion/ or reaching out so QA can try to get more info for us. Feel free to link to this issue if you post there!

**Comment by upperking** [comment]
I am having a strange issue with   "Day0":    Setting. When the date is set closer to the time I export it my cpu usage doubles or triples when using the grid but when I set the date to 3 months later it runs way less in cpu% why would that make such a big difference changing the dates in the servergrid.json
